[tool.poetry]
name = "monarch-ingest"
version = "0.1.1"
description = ""
authors = [
    "Kevin Schaper <kevinschaper@gmail.com>",
    "Victoria Soesanto <victoria.soesanto@cuanschutz.edu>",
    "Kent Shefchek <kent@tislab.org>",
    "The Monarch Initiative <info@monarchinitiative.org>"
]

[tool.poetry.dependencies]
python = "^3.8"
autoflake = "^1.4"
flake8 = "^3.9.2"
isort = "^5.9.1"
importlib-metadata = "^4.6.1"
mkdocs = "^1.2.2"
mkdocs-material = "^7.2.4"
kgx = ">=1.5.3, <1.6"
koza = "^0.1.7"
biolink_model_pydantic = "0.1.2"
dagit = ">0.13, <0.14"
dagster = ">0.13, <0.14"
kghub_downloader = ">=0.1.0"
numpy = "^1.22"
kghub-downloader = "0.1.12"

[tool.poetry.dev-dependencies]
pytest = "^5.2"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"

[tool.black]
line_length = 90
skip-string-normalization = true

[tool.isort]
profile = "black"
line_length = 90
multi_line_output = 3
include_trailing_comma = true
