[tool.poetry]
name = "monarch-ingest"
version = "0.3.8"
description = ""
authors = [
    "The Monarch Initiative <info@monarchinitiative.org>",
    "Kevin Schaper <kevinschaper@gmail.com>",
    "Victoria Soesanto <victoria.soesanto@cuanschutz.edu>",
    "Glass Elsarboukh <g.elsarboukh@gmail.com>",
    "Kent Shefchek <kent@tislab.org>",
    "Richard Bruskiewich <richard.bruskiewich@delphinai.com>",
]
packages = [
    { include = "monarch_ingest", from = "src" },
]

[tool.poetry.dependencies]
python = "^3.10"
kghub-downloader = "^0.3.2"
koza = "^0.3.0"
cat-merge = "^0.1.18"
closurizer = "^0.1.7"
monarch-py = "0.6.2"
kgx = "2.0.7"
multi-indexer = "*"
biolink-model = "3.1.1"
# biolink-model = "^3.2.1"
linkml = "^1.5.0"
#linkml-solr = "^0.1.3"
linkml-solr = {git = "https://github.com/linkml/linkml-solr.git", branch = "top_class"}
greenlet = "^1.1.2"
importlib-metadata = "^4.6.1"
sh = "^1.14.3"
typer = "^0.7"
typer-cli = "^0.0.13"
loguru = "*"
linkml-validator = "^0.4.5"

[tool.poetry.group.dev]
optional = true

[tool.poetry.group.dev.dependencies]
autoflake = "^1.4"
flake8 = "^3.9.2"
isort = "^5.9.1"
mkdocs = "^1.3.0"
mkdocs-material = "^8.2.9"
pytest = "^7.1.1"
black = "^23.3.0"

[tool.poetry.scripts]
ingest = "monarch_ingest.main:typer_app"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"

[tool.black]
line_length = 120
skip-string-normalization = true

[tool.isort]
profile = "black"
line_length = 120
multi_line_output = 3
include_trailing_comma = true
